apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: be-controller-ui
    version: latest
  name: be-controller-ui
  namespace: hyperpilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-controller-ui
  template:
    metadata:
      labels:
        app: be-controller-ui
        version: latest
    spec:
      containers:
      - name: be-controller-ui
        image: adrianliaw/be-controller-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          hostPort: 3000
          protocol: TCP
        env:
        - name: INFLUXDB_HOST
          value: influxsrv.hyperpilot
        - name: INFLUXDB_PORT
          value: "8086"
        - name: INFLUXDB_USER
          value: root
        - name: INFLUXDB_PASS
          value: default
        - name: INFLUXDB_NAME_CONTROLLER
          value: be_controller
        resources:
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: be-controller-ui
  name: be-controller-ui
  namespace: hyperpilot
spec:
  type: ClusterIP
  ports:
  - name: be-controller-ui
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: be-controller-ui
